### ISSUE TITLE
ZFS 0.8.0 release compatibility?

### ISSUE THREAD

**Issue by 12wrigja** [lorenz/torcx-zfs#6]
In release 0.8.0, it seems that the SPL has been inlined into the ZoL repository, and causes the build.sh script to fail.

After removing this the call to configure the SPL separately, I can get a build to compile and package, but using it on CoreOS 2079.5.1 seems to fail due to a Lua module missing? I see the following in the kernel logs:

[  250.214209] zfs: Unknown symbol lua_pcallk (err -2)
[  250.220688] zfs: Unknown symbol lua_touserdata (err -2)
[  250.226781] zfs: Unknown symbol lua_pushlightuserdata (err -2)
[  250.226823] zfs: Unknown symbol lua_atpanic (err -2)
[  250.239271] zfs: Unknown symbol lua_isnumber (err -2)
[  250.239366] zfs: Unknown symbol lua_sethook (err -2)
[  250.250923] zfs: Unknown symbol luaopen_string (err -2)
[  250.250960] zfs: Unknown symbol lua_getfield (err -2)
[  250.262985] zfs: Unknown symbol lua_next (err -2)
[  250.263080] zfs: Unknown symbol lua_gettop (err -2)
[  250.274097] zfs: Unknown symbol lua_pushvfstring (err -2)
[  250.274171] zfs: Unknown symbol lua_tointegerx (err -2)
[  250.286427] zfs: Unknown symbol lua_pushnumber (err -2)
[  250.292541] zfs: Unknown symbol lua_remove (err -2)
[  250.292567] zfs: Unknown symbol lua_setfield (err -2)
[  250.304125] zfs: Unknown symbol lua_isstring (err -2)
[  250.304158] zfs: Unknown symbol lua_pushvalue (err -2)
[  250.304204] zfs: Unknown symbol lua_pushnil (err -2)
[  250.304241] zfs: Unknown symbol luaL_error (err -2)
[  250.327404] zfs: Unknown symbol lua_settop (err -2)
[  250.333125] zfs: Unknown symbol lua_pushcclosure (err -2)
[  250.339420] zfs: Unknown symbol lua_pushfstring (err -2)
[  250.345611] zfs: Unknown symbol lua_tolstring (err -2)
[  250.351595] zfs: Unknown symbol lua_type (err -2)
[  250.357098] zfs: Unknown symbol lua_pushboolean (err -2)
[  250.363284] zfs: Unknown symbol lua_tonumberx (err -2)
[  250.369301] zfs: Unknown symbol lua_settable (err -2)
[  250.375247] zfs: Unknown symbol lua_setmetatable (err -2)
[  250.381529] zfs: Unknown symbol lua_close (err -2)
[  250.387170] zfs: Unknown symbol luaL_newmetatable (err -2)
[  250.393612] zfs: Unknown symbol lua_newuserdata (err -2)
[  250.401964] zfs: Unknown symbol lua_newstate (err -2)
[  250.407860] zfs: Unknown symbol lua_setglobal (err -2)
[  250.413851] zfs: Unknown symbol lua_error (err -2)
[  250.419488] zfs: Unknown symbol lua_absindex (err -2)
[  250.425438] zfs: Unknown symbol lua_checkstack (err -2)
[  250.431501] zfs: Unknown symbol lua_gettable (err -2)
[  250.437374] zfs: Unknown symbol lua_pushstring (err -2)
[  250.443466] zfs: Unknown symbol luaL_argerror (err -2)
[  250.449425] zfs: Unknown symbol luaL_loadbufferx (err -2)
[  250.455783] zfs: Unknown symbol luaopen_base (err -2)
[  250.461684] zfs: Unknown symbol luaopen_table (err -2)
[  250.467701] zfs: Unknown symbol lua_replace (err -2)
[  250.473510] zfs: Unknown symbol luaL_traceback (err -2)
[  250.479632] zfs: Unknown symbol luaopen_coroutine (err -2)
[  250.486079] zfs: Unknown symbol lua_toboolean (err -2)
[  250.492061] zfs: Unknown symbol lua_typename (err -2)
[  250.497999] zfs: Unknown symbol lua_createtable (err -2)
[  250.504186] zfs: Unknown symbol lua_pushinteger (err -2)

Any ideas how to fix this?

**Comment by lorenz** [comment]
The master branch is currently not compatible with 0.8. I have a branch which works with 0.8 though. I'll publish it soonish.

**Comment by lorenz** [comment]
This is fixed now, when the internal CI finishes it will merge ZoL 0.8 support into master.

**Comment by 12wrigja** [comment]
Thank you so much! Giving it a try now.
